import test from 'node:test';import assert from'node:assert/strict';import fs from'node:fs';import path from'node:path';import os from'node:os';
import {createRuntime,walk}from'../src/runtime.mjs';import {parse,serialize}from'../src/parser.mjs';import {Versions}from'../src/versions.mjs';import {abstractPrograms,synthesize}from'../src/learning.mjs';import {sameFacts,key}from'../src/values.mjs';
import {coverage}from'../experiments/support/util.mjs';import {families,trace,demonstration,context}from'../experiments/support/completion.mjs';
const vm=await createRuntime();
const run=(source,input={})=>{vm.registerSource('testCase',source);return vm.run('testCase',input).value;};
const prefix='@input input\n';
test('multiline declarations have no dot terminator',()=>assert.equal(run(prefix+'@a data.identity\nvalue 4\n@output number.add\nleft $a\nright 3'),7));
test('forward references are topologically scheduled',()=>assert.equal(run(prefix+'@output number.add left $a right 2\n@a data.identity value 5'),7));
test('duplicate SSA producers are rejected',()=>assert.throws(()=>parse(prefix+'@a data.identity value 1\n@a data.identity value 2\n@output data.identity value $a'),/duplicate/));
test('unknown value wire is rejected',()=>assert.throws(()=>parse(prefix+'@output data.identity value $missing'),/unresolved/));
test('unknown handle wire is rejected',()=>assert.throws(()=>parse(prefix+'@output program.inspect reference ~missing'),/unresolved/));
test('cyclic references are rejected',()=>assert.throws(()=>parse(prefix+'@a data.identity value $b\n@b data.identity value $a\n@output data.identity value $a'),/cyclic/));
test('module output required',()=>assert.throws(()=>parse(prefix),/@input and @output/));
test('input means call arguments',()=>assert.throws(()=>parse('@input data.identity value 2\n@output data.identity value $input'),/input command/));
test('unclosed literal rejected',()=>assert.throws(()=>parse(prefix+'@output data.identity value "oops'),/quote/));
test('literal period is data, not a delimiter',()=>assert.equal(run(prefix+'@output data.identity value "."'),'.'));
test('trailing delimiter rejected by argument contract',()=>assert.throws(()=>run(prefix+'@output data.identity value 7 .'),/pairs/));
test('duplicate argument rejected',()=>assert.throws(()=>run(prefix+'@output data.identity value 1 value 2'),/Duplicate argument/));
test('missing native argument is rejected',()=>assert.throws(()=>run(prefix+'@output number.add left 1'),/Missing argument/));
test('unknown native argument is rejected',()=>assert.throws(()=>run(prefix+'@output number.add left 1 right 2 magic 3'),/Unexpected argument/));
test('raw text supports $ interpolation and multiline bodies',()=>assert.equal(run(prefix+'@name data.identity value "Ana"\n@output text\nHello $name.\nA second line.'),'Hello Ana.\nA second line.'));
test('quoted text also interpolates ordinary $ values',()=>assert.equal(run(prefix+'@x data.identity value "Ana"\n@output data.identity value "Hello $x."'),'Hello Ana.'));
test('literal dollar escape',()=>assert.equal(run(prefix+'@output text\nPrice $$5'),'Price $5'));
test('inserting text does not reparse instructions',()=>assert.equal(run(prefix+'@v data.get source $input key "text"\n@output text\n$v',{text:'@evil number.add left 1 right 2'}),'@evil number.add left 1 right 2'));
test('opaque values cannot silently interpolate as strings',()=>assert.throws(()=>run(prefix+'@output text\n$input',{}),/non-scalar/));
test('~ reference exposes producer and epoch, not just payload',()=>{const r=run(prefix+'@a data.identity value 5\n@output program.inspect reference ~a');assert.equal(r.value,5);assert.equal(r.command,'data.identity');assert.equal(r.epoch,'session');assert.equal(r.sourceHash.length,64);assert.ok(Object.isFrozen(r));});
test('nested .sop command is called like a native command',()=>assert.equal(vm.run('language.say.atAdded',{person:'A',place:'B'}).value,'A is now at B.'));
test('path-derived native and SOP names resolve without type namespaces',()=>{assert.equal(vm.registry.get('number.add').kind,'mjs');assert.equal(vm.registry.get('tasks.respond').kind,'sop');assert.ok(vm.registry.get('tasks.respond').path.endsWith('/tasks/respond.sop'));});
test('cannot overwrite a native command by source injection',()=>assert.throws(()=>vm.registerSource('number.add',prefix+'@output data.identity value 8'),/native command/));
test('invalid command paths are rejected',()=>assert.throws(()=>vm.registerSource('../../escape',prefix+'@output data.identity value 8'),/Invalid command/));
test('missing command has no heuristic fallback',()=>assert.throws(()=>vm.run('does.not.exist',{}),/Unknown command/));
test('parse/serialize preserves ordinary text behavior',()=>{const src=prefix+'@a data.identity value "A"\n@output text\nHello $a.\nNext line.';assert.equal(run(src),run(serialize(parse(src))));});
test('every materialized SOP file parses and its static calls resolve',()=>{for(const [name,r]of vm.registry)if(r.kind==='sop'){const ast=parse(vm.source(name));for(const n of ast.nodes)assert.ok(vm.registry.has(n.command),`${name}: ${n.command}`);}});
test('language parsing is executed by SOP constructions',()=>assert.deepEqual(vm.run('language.parse',{text:'Ana gave book to Bob.'}).value,[['give','Ana','Bob','book']]));
test('unsupported negation is not asserted positively',()=>assert.deepEqual(vm.run('language.parse',{text:'Ana did not take book.'}).value,[]));
test('incomplete coverage yields unknown, not false',()=>{const r=vm.attempt('tasks.advance',{before:[['at','A','L'],['at','O','L']],event:['take','A','O']});assert.equal(r.status,'unknown');});
test('stale coverage token yields unknown',()=>{const r=vm.attempt('tasks.advance',{before:[['at','A','L'],['at','O','L']],event:['take','A','O'],coverage:coverage([])});assert.equal(r.status,'unknown');});
test('closed coverage permits an absent-condition conclusion',()=>{const before=[['at','A','L'],['at','O','L']];const r=vm.run('tasks.advance',{before,event:['take','A','O'],coverage:coverage(before)}).value;assert.ok(r.after.some(f=>key(f)===key(['holds','A','O'])));});
test('positive counterevidence blocks take without needing closure',()=>{const before=[['at','A','L'],['at','O','L'],['holds','B','O']];const r=vm.run('tasks.advance',{before,event:['take','A','O']}).value;assert.ok(sameFacts(r.after,before));});
test('state execution does not mutate input snapshot',()=>{const before=[['at','A','L'],['at','O','L']],saved=key(before);vm.run('tasks.advance',{before,event:['take','A','O'],coverage:coverage(before)});assert.equal(key(before),saved);});
test('explicit work budget has an unknown outcome',()=>assert.equal(vm.attempt('tasks.ancestors',{facts:[['parent','a','b']]},{budget:1}).status,'unknown'));
test('fixed point on a cycle terminates without erasing reflexive consequences',()=>{const r=vm.run('tasks.ancestors',{facts:[['parent','a','b'],['parent','b','a']]}).value;assert.ok(r.facts.some(f=>key(f)===key(['ancestor','a','a'])));});
test('delta summary does not silently drop unsupported relations',()=>assert.equal(vm.attempt('tasks.summarize',{before:[],after:[['likes','A','B']]}).status,'unknown'));
test('no support preserves both ambiguity branches',()=>assert.equal(vm.run('tasks.ambiguity',{text:'A saw B with the T.',facts:[]}).value.candidates.length,2));
test('conflicting supports preserve ambiguity rather than majority voting',()=>assert.equal(vm.run('tasks.ambiguity',{text:'A saw B with the T.',facts:[['uses','A','T'],['has','B','T']]}).value.status,'ambiguous'));
test('abstraction outputs an executable SOP source with shared slots',()=>{const sources=[0,1,2].map(i=>demonstration(trace(families[0],[`P${i}`,`O${i}`])));const fit=abstractPrograms(sources);assert.equal(fit.slots,2);assert.deepEqual(run(fit.source,{context:context(trace(families[0],['newP','newO']))}),[['store','newP','newO']]);});
test('abstraction is insensitive to local producer renaming',()=>{const a=demonstration(trace(families[0],['P','O']));const b=demonstration(trace(families[0],['X','Y'])).replaceAll('first','uno').replaceAll('second','dos');assert.equal(abstractPrograms([a,b]).slots,2);});
test('unmatched graph topology is not presented as learned alignment',()=>assert.throws(()=>abstractPrograms([prefix+'@output data.identity value 1',prefix+'@x data.identity value 2\n@output data.identity value $x']),/Unaligned/));
test('unbound target slot explicitly abstains',()=>{const s=[1,2].map(i=>demonstration([['see','P'+i],['ask','P'+i],['answer','Z'+i]]));vm.registerSource('testUnbound',abstractPrograms(s).source);assert.equal(vm.attempt('testUnbound',{context:context([['see','A'],['ask','A']])}).status,'unknown');});
test('synthesis returns unknown outside search budget',()=>{const r=synthesize(vm,[{input:{a:2,b:3},output:17},{input:{a:4,b:5},output:41}],[],{operations:['number.add'],maxNodes:3,maxCandidates:1});assert.equal(r.status,'unknown');});
test('only supplied generic operators are searched',()=>{const r=synthesize(vm,[{input:{a:2,b:3},output:6},{input:{a:4,b:5},output:20}],[],{operations:['number.multiply'],maxNodes:1});assert.equal(r.status,'found');assert.ok(r.source.includes('number.multiply'));assert.ok(!r.source.includes('number.add'));});
test('source promotion rejects conflicting predictions',()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'sop-test-'));try{const v=new Versions(tmp),good=prefix+'@output data.identity value 2',bad=prefix+'@output data.identity value 3';const tests=[{input:{},output:2}];assert.ok(v.propose(vm,'deployed.test',good,tests).accepted);const old=v.active['deployed.test'];assert.ok(!v.propose(vm,'deployed.test',bad,tests).accepted);assert.equal(v.active['deployed.test'],old);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});
test('native code does not contain the test-domain vocabulary',()=>{const root=path.resolve(import.meta.dirname,'..');const files=walk(path.join(root,'src')).concat(walk(path.join(root,'commands')).filter(f=>f.endsWith('.mjs')));for(const f of files)assert.ok(!/['"](?:travel|take|drop|give|holds|picked|ancestor)['"]/.test(fs.readFileSync(f,'utf8')),f);});
test('active modules never import experiment or oracle code',()=>{const root=path.resolve(import.meta.dirname,'..');for(const f of walk(path.join(root,'src')).concat(walk(path.join(root,'commands')).filter(f=>f.endsWith('.mjs'))))assert.ok(!/(?:from\s*|import\s*\()["'][^"']*(?:experiments|oracle)/.test(fs.readFileSync(f,'utf8')),f);});
test('loader rejects a native/SOP same-path collision',async()=>{const tmp=fs.mkdtempSync(path.join(os.tmpdir(),'sop-collision-'));try{fs.writeFileSync(path.join(tmp,'x.mjs'),'export default ()=>1;');fs.writeFileSync(path.join(tmp,'x.sop'),prefix+'@output data.identity value 2');await assert.rejects(createRuntime(tmp),/Ambiguous/);}finally{fs.rmSync(tmp,{recursive:true,force:true});}});

test('unsupported event is unknown, not an observed no-op',()=>assert.equal(vm.attempt('tasks.advance',{before:[],event:['teleport','A','B'],coverage:coverage([])}).status,'unknown'));
test('raw text programs are not silently anti-unified as named arguments',()=>assert.throws(()=>abstractPrograms([prefix+'@output text hello Alice',prefix+'@output text hello Bob']),/Raw-text/));
test('freshness of a reusable source index is explicitly checkable',async()=>{const {SourceIndex}=await import('../src/retrieval.mjs');vm.registerSource('indexProbe',prefix+'@output data.identity value 1');const i=new SourceIndex(vm,['indexProbe']);assert.equal(i.assertFresh(vm),true);vm.registerSource('indexProbe',prefix+'@output data.identity value 2');assert.throws(()=>i.assertFresh(vm),/Stale/);});
test('known but blocked take remains a complete no-op',()=>{const before=[['at','A','left'],['at','O','right']];const r=vm.attempt('tasks.advance',{before,event:['take','A','O'],coverage:coverage(before)});assert.equal(r.status,'complete');assert(sameFacts(r.value.after,before));});
test('documented executable examples match their described results',async()=>{
 const root=path.resolve(import.meta.dirname,'../examples');
 for(const name of ['add','inspect','sentence','take-readable'])vm.registerSource('example_'+name.replace('-','_'),fs.readFileSync(path.join(root,name+'.sop'),'utf8'));
 assert.equal(vm.run('example_add',{a:2,b:3}).value,5);
 assert.equal(vm.run('example_inspect').value.value,7);
 assert.equal(vm.run('example_sentence',{person:'Alice',object:'book'}).value,'Alice now holds book.');
 const original=[...vm.registry.keys()].find(n=>n.startsWith('knowledge.transitions.model101.take.'));
 const episodes=fs.readFileSync(path.resolve(import.meta.dirname,'../data/transitions101.jsonl'),'utf8').trim().split('\n').map(JSON.parse).filter(e=>e.event[0]==='take');
 const effects=v=>v.map(({sign,fact})=>({sign,fact}));
 for(const e of episodes){const frame={...e,coverage:coverage(e.before)};assert.deepEqual(effects(vm.run('example_take_readable',frame).value),effects(vm.run(original,frame).value));}
});
test('a knowledge observation is produced by an ordinary SOP circuit',()=>{
 const r=vm.run('knowledge.episodes.initial').value;
 assert.equal(r.status,'authored-observation');
 assert(sameFacts(r.facts,[['at','Alice','lab'],['at','book','lab']]));
 assert.match(r.source,/Alice/);
});
